baseURL = "https://higebobo.github.io/hugo-diary"
languageCode = "en-us"
defaultContentLanguage = "ja"
title = "Hugo Diary"
theme = "hugo-theme-diary"
copyright = "This is a customized copyright."
# googleAnalytics = "UA-123-45"
#uglyurls = false

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "Themed by Diary."
enableGitalk = false
#disableToC = true
disableDarkMode=true

#[[params.customCSS]]
#href = "css/style.css"

#[params.gitalk]
#  owner = "user"
#  repo = "repo name"
#  client_id = "your client id"
#  client_secret = "your client secret"

[taxonomies]
tag = "tags"
#category = "categories"

[[menu.main]]
url = "/index.html"
name = "Home"
weight = 1
#[[menu.main]]
#url = "/categories"
#name = "Categories"
#weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 2
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 3
[[menu.main]]
url = "/about/"
name = "About"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5

#[languages]
[languages.ja]
title = "尾張日記"
dateFormat = "2006年1月2日"
copyright = "ひげぼうぼう"
subtitle = "徒然なるままに"
[[languages.ja.menu.main]]
url = "/index.html"
name = "ホーム"
weight = 1
[[languages.ja.menu.main]]
url = "/tags"
name = "タグ"
weight = 2
[[languages.ja.menu.main]]
url = "/posts"
name = "アーカイブ"
weight = 3
[[languages.ja.menu.main]]
url = "/about/"
name = "このサイトについて"
weight = 4
[[languages.ja.menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5
